/**
 * Admin Users Management Mock Dataset
 */

export const usersMockData = [
  {
    id: 'usr-1',
    name: 'Alex Rivera',
    username: '@alexrivera',
    email: 'alex@orbitsocial.com',
    role: 'Creator',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-06-14',
    lastActive: '2 mins ago',
    connectedPlatforms: ['Instagram', 'YouTube', 'LinkedIn', 'X'],
    totalPosts: 142,
    totalCampaigns: 12,
    engagementRate: '8.4%'
  },
  {
    id: 'usr-2',
    name: 'Sarah Johnson',
    username: '@sarahj_mktg',
    email: 'sarah@orbitsocial.com',
    role: 'Manager',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-03-22',
    lastActive: '15 mins ago',
    connectedPlatforms: ['LinkedIn', 'Facebook'],
    totalPosts: 89,
    totalCampaigns: 24,
    engagementRate: '7.8%'
  },
  {
    id: 'usr-3',
    name: 'Michael Brown',
    username: '@mbrown_dev',
    email: 'michael@orbitsocial.com',
    role: 'User',
    status: 'Inactive',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-08-10',
    lastActive: '14 days ago',
    connectedPlatforms: ['X'],
    totalPosts: 14,
    totalCampaigns: 2,
    engagementRate: '4.2%'
  },
  {
    id: 'usr-4',
    name: 'Emma Wilson',
    username: '@emma_designs',
    email: 'emma@orbitsocial.com',
    role: 'Creator',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-09-01',
    lastActive: '1 hour ago',
    connectedPlatforms: ['Instagram', 'Pinterest'],
    totalPosts: 210,
    totalCampaigns: 18,
    engagementRate: '9.6%'
  },
  {
    id: 'usr-5',
    name: 'David Kim',
    username: '@davidkimtech',
    email: 'david@orbitsocial.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-01-10',
    lastActive: 'Just now',
    connectedPlatforms: ['Instagram', 'YouTube', 'LinkedIn', 'X', 'Pinterest', 'Facebook'],
    totalPosts: 340,
    totalCampaigns: 45,
    engagementRate: '8.9%'
  },
  {
    id: 'usr-6',
    name: 'Sophia Martinez',
    username: '@sophiam_creative',
    email: 'sophia@orbitsocial.com',
    role: 'Creator',
    status: 'Suspended',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-10-15',
    lastActive: '5 days ago',
    connectedPlatforms: ['Instagram'],
    totalPosts: 45,
    totalCampaigns: 3,
    engagementRate: '5.1%'
  },
  {
    id: 'usr-7',
    name: 'James Taylor',
    username: '@jtaylor_marketing',
    email: 'james@orbitsocial.com',
    role: 'Manager',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-11-20',
    lastActive: '3 hours ago',
    connectedPlatforms: ['LinkedIn', 'X'],
    totalPosts: 112,
    totalCampaigns: 16,
    engagementRate: '7.2%'
  },
  {
    id: 'usr-8',
    name: 'Olivia Chen',
    username: '@oliviachen_ai',
    email: 'olivia@orbitsocial.com',
    role: 'Creator',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2026-01-05',
    lastActive: '45 mins ago',
    connectedPlatforms: ['YouTube', 'X', 'LinkedIn'],
    totalPosts: 68,
    totalCampaigns: 8,
    engagementRate: '9.1%'
  },
  {
    id: 'usr-9',
    name: 'Daniel Anderson',
    username: '@danderson_ops',
    email: 'daniel@orbitsocial.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-02-14',
    lastActive: '10 mins ago',
    connectedPlatforms: ['Instagram', 'LinkedIn'],
    totalPosts: 195,
    totalCampaigns: 30,
    engagementRate: '8.0%'
  },
  {
    id: 'usr-10',
    name: 'Chloe Bennett',
    username: '@chloeb_content',
    email: 'chloe@orbitsocial.com',
    role: 'User',
    status: 'Inactive',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2025-12-01',
    lastActive: '30 days ago',
    connectedPlatforms: ['Facebook'],
    totalPosts: 8,
    totalCampaigns: 1,
    engagementRate: '3.5%'
  },
  {
    id: 'usr-11',
    name: 'Liam Noah',
    username: '@liamnoah_vlog',
    email: 'liam@orbitsocial.com',
    role: 'Creator',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2026-01-18',
    lastActive: '4 hours ago',
    connectedPlatforms: ['YouTube', 'Instagram'],
    totalPosts: 54,
    totalCampaigns: 6,
    engagementRate: '8.7%'
  },
  {
    id: 'usr-12',
    name: 'Isabella Rossi',
    username: '@isabellar_fashion',
    email: 'isabella@orbitsocial.com',
    role: 'Creator',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80',
    joinedDate: '2026-02-01',
    lastActive: '20 mins ago',
    connectedPlatforms: ['Instagram', 'Pinterest'],
    totalPosts: 38,
    totalCampaigns: 5,
    engagementRate: '9.4%'
  }
]
