// ═══════════════════════════════════════════════════════════════════
// Publishing Module — Mock Data
// ═══════════════════════════════════════════════════════════════════

export const publishingDashboardData = {
  stats: [
    { label: 'Total Published', value: '1,247', change: '+12%', positive: true, icon: '📤', accent: 'bg-emerald-50 dark:bg-emerald-950/40' },
    { label: 'Scheduled Posts', value: '38', change: '+5%', positive: true, icon: '📅', accent: 'bg-indigo-50 dark:bg-indigo-950/40' },
    { label: 'Queue Size', value: '24', change: '-3%', positive: true, icon: '📋', accent: 'bg-amber-50 dark:bg-amber-950/40' },
    { label: 'Failed Posts', value: '7', change: '+2', positive: false, icon: '⚠️', accent: 'bg-rose-50 dark:bg-rose-950/40' },
    { label: 'Success Rate', value: '94.3%', change: '+1.2%', positive: true, icon: '🎯', accent: 'bg-sky-50 dark:bg-sky-950/40' },
    { label: 'Platforms Connected', value: '6', change: '—', positive: true, icon: '🔗', accent: 'bg-purple-50 dark:bg-purple-950/40' },
  ],
  recentActivity: [
    { id: 1, action: 'Post published', platform: 'Instagram', campaign: 'Summer Sale 2026', time: '5 min ago', status: 'published' },
    { id: 2, action: 'Post scheduled', platform: 'LinkedIn', campaign: 'Thought Leadership', time: '18 min ago', status: 'scheduled' },
    { id: 3, action: 'Post failed', platform: 'Facebook', campaign: 'Product Launch', time: '45 min ago', status: 'failed' },
    { id: 4, action: 'Post published', platform: 'X', campaign: 'Daily Tips', time: '1 hour ago', status: 'published' },
    { id: 5, action: 'Post queued', platform: 'Pinterest', campaign: 'Visual Stories', time: '2 hours ago', status: 'queued' },
    { id: 6, action: 'Post published', platform: 'YouTube', campaign: 'Tutorial Series', time: '3 hours ago', status: 'published' },
  ],
  todaySchedule: [
    { id: 1, time: '09:00 AM', platform: 'Instagram', content: 'Morning motivation carousel', status: 'published' },
    { id: 2, time: '11:30 AM', platform: 'LinkedIn', content: 'Industry insights article', status: 'published' },
    { id: 3, time: '02:00 PM', platform: 'X', content: 'Product tip thread', status: 'scheduled' },
    { id: 4, time: '04:30 PM', platform: 'Facebook', content: 'Community Q&A post', status: 'scheduled' },
    { id: 5, time: '07:00 PM', platform: 'YouTube', content: 'Tutorial episode #14', status: 'queued' },
  ],
  upcomingSchedule: [
    { id: 1, date: 'Tomorrow', time: '10:00 AM', platform: 'Instagram', content: 'Behind-the-scenes reel' },
    { id: 2, date: 'Tomorrow', time: '02:00 PM', platform: 'LinkedIn', content: 'Case study post' },
    { id: 3, date: 'Aug 7', time: '09:00 AM', platform: 'Pinterest', content: 'Infographic — Top 10 Tips' },
    { id: 4, date: 'Aug 7', time: '03:00 PM', platform: 'X', content: 'Poll — Audience preferences' },
    { id: 5, date: 'Aug 8', time: '11:00 AM', platform: 'Facebook', content: 'Customer testimonial video' },
  ],
  publishingStatus: {
    healthy: 4,
    warning: 1,
    error: 1,
    platforms: [
      { name: 'Instagram', status: 'healthy', lastSync: '2 min ago' },
      { name: 'LinkedIn', status: 'healthy', lastSync: '5 min ago' },
      { name: 'Facebook', status: 'warning', lastSync: '15 min ago' },
      { name: 'X', status: 'healthy', lastSync: '1 min ago' },
      { name: 'Pinterest', status: 'healthy', lastSync: '8 min ago' },
      { name: 'YouTube', status: 'error', lastSync: '1 hour ago' },
    ],
  },
}

export const publishingQueueData = [
  { id: 'Q-001', position: 1, platform: 'Instagram', campaign: 'Summer Sale 2026', scheduledTime: '2026-08-05 09:00', priority: 'High', status: 'queued', content: 'New summer collection drop 🔥' },
  { id: 'Q-002', position: 2, platform: 'LinkedIn', campaign: 'Thought Leadership', scheduledTime: '2026-08-05 10:30', priority: 'Medium', status: 'queued', content: 'Industry trends analysis for Q3' },
  { id: 'Q-003', position: 3, platform: 'X', campaign: 'Daily Tips', scheduledTime: '2026-08-05 12:00', priority: 'Low', status: 'queued', content: 'Thread: 5 productivity hacks' },
  { id: 'Q-004', position: 4, platform: 'Facebook', campaign: 'Product Launch', scheduledTime: '2026-08-05 14:00', priority: 'High', status: 'paused', content: 'Introducing our latest feature update' },
  { id: 'Q-005', position: 5, platform: 'Pinterest', campaign: 'Visual Stories', scheduledTime: '2026-08-05 15:30', priority: 'Medium', status: 'queued', content: 'DIY craft tutorial infographic' },
  { id: 'Q-006', position: 6, platform: 'YouTube', campaign: 'Tutorial Series', scheduledTime: '2026-08-05 17:00', priority: 'High', status: 'queued', content: 'Episode 14: Advanced techniques' },
  { id: 'Q-007', position: 7, platform: 'Instagram', campaign: 'User Stories', scheduledTime: '2026-08-06 09:00', priority: 'Medium', status: 'queued', content: 'Customer spotlight: Sarah M.' },
  { id: 'Q-008', position: 8, platform: 'LinkedIn', campaign: 'Recruitment', scheduledTime: '2026-08-06 11:00', priority: 'Low', status: 'queued', content: 'We\'re hiring — Senior Dev' },
  { id: 'Q-009', position: 9, platform: 'X', campaign: 'Engagement', scheduledTime: '2026-08-06 13:00', priority: 'Medium', status: 'paused', content: 'Poll: What feature next?' },
  { id: 'Q-010', position: 10, platform: 'Facebook', campaign: 'Community', scheduledTime: '2026-08-06 16:00', priority: 'Low', status: 'queued', content: 'Friday community roundup' },
]

export const publishingLogsData = [
  { id: 'L-001', date: '2026-08-04 18:32', platform: 'Instagram', campaign: 'Summer Sale 2026', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-002', date: '2026-08-04 16:15', platform: 'LinkedIn', campaign: 'Thought Leadership', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-003', date: '2026-08-04 14:45', platform: 'Facebook', campaign: 'Product Launch', status: 'failed', response: '403 Forbidden — Token expired', retryCount: 3, publishedBy: 'System' },
  { id: 'L-004', date: '2026-08-04 12:00', platform: 'X', campaign: 'Daily Tips', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-005', date: '2026-08-04 10:30', platform: 'Pinterest', campaign: 'Visual Stories', status: 'published', response: '200 OK', retryCount: 1, publishedBy: 'System' },
  { id: 'L-006', date: '2026-08-04 09:00', platform: 'YouTube', campaign: 'Tutorial Series', status: 'failed', response: '500 Internal Server Error', retryCount: 2, publishedBy: 'System' },
  { id: 'L-007', date: '2026-08-03 17:00', platform: 'Instagram', campaign: 'User Stories', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-008', date: '2026-08-03 14:30', platform: 'LinkedIn', campaign: 'Recruitment', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-009', date: '2026-08-03 11:00', platform: 'X', campaign: 'Engagement', status: 'cancelled', response: 'Cancelled by user', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-010', date: '2026-08-03 09:15', platform: 'Facebook', campaign: 'Community', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'System' },
  { id: 'L-011', date: '2026-08-02 16:45', platform: 'Pinterest', campaign: 'Visual Stories', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-012', date: '2026-08-02 13:00', platform: 'YouTube', campaign: 'Tutorial Series', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'System' },
  { id: 'L-013', date: '2026-08-02 10:00', platform: 'Instagram', campaign: 'Summer Sale 2026', status: 'failed', response: '429 Rate Limited', retryCount: 3, publishedBy: 'System' },
  { id: 'L-014', date: '2026-08-01 15:30', platform: 'LinkedIn', campaign: 'Thought Leadership', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
  { id: 'L-015', date: '2026-08-01 11:00', platform: 'X', campaign: 'Daily Tips', status: 'published', response: '200 OK', retryCount: 0, publishedBy: 'Alex Creator' },
]

export const failedPostsData = [
  {
    id: 'F-001',
    platform: 'Facebook',
    campaign: 'Product Launch',
    reason: 'Authentication Error',
    errorMessage: 'OAuth token expired. The access token has been invalidated because the user changed their password or Facebook has changed the session for security reasons.',
    failedAt: '2026-08-04 14:45',
    retryCount: 3,
    content: 'Introducing our latest feature update — smarter scheduling, deeper analytics, and seamless multi-platform publishing.',
  },
  {
    id: 'F-002',
    platform: 'YouTube',
    campaign: 'Tutorial Series',
    reason: 'Server Error',
    errorMessage: 'YouTube API returned 500 Internal Server Error. The upload service is temporarily unavailable. Please retry after a few minutes.',
    failedAt: '2026-08-04 09:00',
    retryCount: 2,
    content: 'Episode 14: Advanced techniques for social media automation — complete walkthrough.',
  },
  {
    id: 'F-003',
    platform: 'Instagram',
    campaign: 'Summer Sale 2026',
    reason: 'Rate Limit Exceeded',
    errorMessage: 'Error 429: Too many requests. You have exceeded the Instagram Graph API rate limit. Wait 15 minutes before retrying.',
    failedAt: '2026-08-02 10:00',
    retryCount: 3,
    content: 'Flash sale alert! 50% off summer collection — limited time only ⏰🔥',
  },
  {
    id: 'F-004',
    platform: 'Pinterest',
    campaign: 'Visual Stories',
    reason: 'Invalid Media',
    errorMessage: 'The uploaded image does not meet Pinterest requirements. Minimum resolution: 600x900px. Current: 400x400px.',
    failedAt: '2026-08-01 16:30',
    retryCount: 1,
    content: 'DIY Home Office Setup — Step-by-step infographic guide.',
  },
  {
    id: 'F-005',
    platform: 'X',
    campaign: 'Engagement',
    reason: 'Content Policy Violation',
    errorMessage: 'This post was flagged by X\'s automated content review. Please review the post content and ensure it complies with platform guidelines.',
    failedAt: '2026-07-31 13:00',
    retryCount: 0,
    content: 'Breaking: Major announcement coming tomorrow. Stay tuned for something incredible! 🚀',
  },
  {
    id: 'F-006',
    platform: 'LinkedIn',
    campaign: 'Recruitment',
    reason: 'Network Timeout',
    errorMessage: 'Connection to LinkedIn API timed out after 30 seconds. This is typically a temporary network issue.',
    failedAt: '2026-07-30 11:00',
    retryCount: 2,
    content: 'We\'re hiring! Looking for a Senior Frontend Engineer to join our growing team.',
  },
  {
    id: 'F-007',
    platform: 'Facebook',
    campaign: 'Community',
    reason: 'Duplicate Content',
    errorMessage: 'Facebook detected this post as duplicate content. A post with identical text was published within the last 24 hours.',
    failedAt: '2026-07-29 09:00',
    retryCount: 0,
    content: 'Friday community roundup — Top discussions and highlights from this week.',
  },
]

export const platformHistoryData = [
  {
    id: 'instagram',
    name: 'Instagram',
    icon: '📸',
    color: 'bg-pink-50 dark:bg-pink-950/40 text-pink-600 dark:text-pink-400',
    totalPosts: 342,
    lastPublished: '5 min ago',
    successRate: 96.2,
    failedPosts: 13,
    recentActivity: [
      { date: '2026-08-04', posts: 4, successful: 4, failed: 0 },
      { date: '2026-08-03', posts: 3, successful: 3, failed: 0 },
      { date: '2026-08-02', posts: 5, successful: 4, failed: 1 },
      { date: '2026-08-01', posts: 2, successful: 2, failed: 0 },
      { date: '2026-07-31', posts: 4, successful: 4, failed: 0 },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: '👤',
    color: 'bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400',
    totalPosts: 287,
    lastPublished: '45 min ago',
    successRate: 91.6,
    failedPosts: 24,
    recentActivity: [
      { date: '2026-08-04', posts: 3, successful: 2, failed: 1 },
      { date: '2026-08-03', posts: 2, successful: 2, failed: 0 },
      { date: '2026-08-02', posts: 4, successful: 4, failed: 0 },
      { date: '2026-08-01', posts: 3, successful: 3, failed: 0 },
      { date: '2026-07-31', posts: 2, successful: 1, failed: 1 },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    color: 'bg-sky-50 dark:bg-sky-950/40 text-sky-600 dark:text-sky-400',
    totalPosts: 198,
    lastPublished: '18 min ago',
    successRate: 97.5,
    failedPosts: 5,
    recentActivity: [
      { date: '2026-08-04', posts: 2, successful: 2, failed: 0 },
      { date: '2026-08-03', posts: 2, successful: 2, failed: 0 },
      { date: '2026-08-02', posts: 1, successful: 1, failed: 0 },
      { date: '2026-08-01', posts: 3, successful: 3, failed: 0 },
      { date: '2026-07-31', posts: 2, successful: 2, failed: 0 },
    ],
  },
  {
    id: 'x',
    name: 'X (Twitter)',
    icon: '𝕏',
    color: 'bg-slate-50 dark:bg-slate-800/60 text-slate-700 dark:text-slate-300',
    totalPosts: 456,
    lastPublished: '1 hour ago',
    successRate: 93.4,
    failedPosts: 30,
    recentActivity: [
      { date: '2026-08-04', posts: 5, successful: 5, failed: 0 },
      { date: '2026-08-03', posts: 6, successful: 5, failed: 1 },
      { date: '2026-08-02', posts: 4, successful: 4, failed: 0 },
      { date: '2026-08-01', posts: 7, successful: 6, failed: 1 },
      { date: '2026-07-31', posts: 5, successful: 5, failed: 0 },
    ],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    icon: '📌',
    color: 'bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400',
    totalPosts: 124,
    lastPublished: '2 hours ago',
    successRate: 95.2,
    failedPosts: 6,
    recentActivity: [
      { date: '2026-08-04', posts: 2, successful: 2, failed: 0 },
      { date: '2026-08-03', posts: 1, successful: 1, failed: 0 },
      { date: '2026-08-02', posts: 2, successful: 2, failed: 0 },
      { date: '2026-08-01', posts: 1, successful: 0, failed: 1 },
      { date: '2026-07-31', posts: 3, successful: 3, failed: 0 },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    icon: '🎬',
    color: 'bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400',
    totalPosts: 87,
    lastPublished: '3 hours ago',
    successRate: 89.7,
    failedPosts: 9,
    recentActivity: [
      { date: '2026-08-04', posts: 1, successful: 0, failed: 1 },
      { date: '2026-08-03', posts: 1, successful: 1, failed: 0 },
      { date: '2026-08-02', posts: 1, successful: 1, failed: 0 },
      { date: '2026-08-01', posts: 0, successful: 0, failed: 0 },
      { date: '2026-07-31', posts: 2, successful: 2, failed: 0 },
    ],
  },
]
