"""implement_content_scheduling_and_campaign_models

Revision ID: 8efde741079e
Revises: e924225ef135
Create Date: 2026-07-19 23:04:40.011048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efde741079e'
down_revision: Union[str, Sequence[str], None] = 'e924225ef135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_social_accounts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'social_account_id')
    )
    op.add_column('campaigns', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('campaigns', sa.Column('objective', sa.String(length=250), nullable=True))
    op.add_column('campaigns', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('title', sa.String(length=150), nullable=True))
    op.add_column('posts', sa.Column('caption', sa.String(length=2000), nullable=True))
    op.add_column('posts', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('media_file_path', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('posts_social_account_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'social_account_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint('unique_workspace_user', 'workspace_members', ['workspace_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_workspace_user', 'workspace_members', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('posts', sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_social_account_id_fkey'), 'posts', 'social_accounts', ['social_account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'timezone')
    op.drop_column('posts', 'media_file_path')
    op.drop_column('posts', 'content_type')
    op.drop_column('posts', 'caption')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'user_id')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'category')
    op.drop_column('campaigns', 'priority')
    op.drop_column('campaigns', 'objective')
    op.drop_column('campaigns', 'description')
    op.drop_table('post_social_accounts')
    # ### end Alembic commands ###
